version: '3.4'


volumes:
  SQLData:
    driver: local

services:
  quixduell.blazor:
    image: ${DOCKER_REGISTRY-}quixduellblazor
    build:
      context: .
      dockerfile: Quixduell/Quixduell.Blazor/Dockerfile
    environment:
     - EmailConfiguration=SMTP #SendGrid or SMTP
     - SMTPEmailConfiguration__DefaultSenderMail=support@linder-warmbach.de
     - SMTPEmailConfiguration__UseSSL=False
     - SMTPEmailConfiguration__SmtpPort=1025
     - SMTPEmailConfiguration__SmtpServer=quixduell.Mailserver


  quixduell.SQLServer:
    container_name: azuresql
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
     - ACCEPT_EULA=YES
     - MSSQL_PID=Developer 
    volumes:
      - SQLData:/var/opt/mssql

  quixduell.Mailserver:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

