version: '3.4'


volumes:
  SQLData:
    driver: local

services:
  quixduell.blazor:
    image: ${DOCKER_REGISTRY-}quixduellblazor
    build:
      context: .
      dockerfile: Quixduell/Quixduell.Blazor/Dockerfile


  quixduell.SQLServer:
    container_name: azuresql
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
     - ACCEPT_EULA=YES
     - MSSQL_PID=Developer 
    volumes:
      - SQLData:/var/opt/mssql

