# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - quizzzmewebapp(Production), Build and deploy DotnetCore app

on:
  push:
    branches:
      - main
 

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master


    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Build with dotnet
      run: dotnet build .\Quixduell\Quixduell.Blazor\Quixduell.Blazor.csproj  --configuration Release

    - name: dotnet publish
      run: dotnet publish .\Quixduell\Quixduell.Blazor\Quixduell.Blazor.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: quixduellwebapp
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_61CEF47A49A54F9B880A171DB0725CC4 }}
        package: ${{env.DOTNET_ROOT}}/myapp

